name: main
on:
  workflow_dispatch:
  # push:
  schedule:
    - cron: '10 17 * * *'
permissions:
  contents: read
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v6
      - name: 创建node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: ./api/package-lock.json
      - name: 🔧 检查GitHub CLI
        run: |
          if ! command -v gh >/dev/null 2>&1; then
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt update
            sudo apt install gh -y
          fi
          gh --version
      - name: Cache node_modules in api directory
        id: cache-npm
        uses: actions/cache@v5
        with:
          path: ./api/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./api/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies #安装依赖
        run: npm ci
      - name: Cache node modules # 缓存安装的依赖
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }} # 使用 package-lock.json 内容生成唯一缓存键  
      - name: 签到
        run: npm run main
        env:
          USERINFO: ${{ secrets.USERINFO }}
          PAT: ${{ secrets.PAT }}
          GITHUB_REPOSITORY: ${{ github.repository }}
